version: "3"

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    restart: always
    environment:
      POSTGRES_PASSWORD: dev

    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data: